title: SVG Cube - THREE.JS
description: >-
  Small experiment rendering a cube in SVG using the SVGRenderer from THREE.JS
baseurl: "/cube-threejs-svg/dist/"

include: ["_pages"] # if we don't include pages, livereload is broken
exclude: ["_webpack"]

source: src
destination: dist

# set up default layouts so we don't have to add them on each pages
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

